stages:
  - build

build_and_push_model_backend:
  stage: build
  image: docker:24.0
  services:
    - docker:24.0-dind
  variables:
    # Target the model-backend repo's registry (not docker-compose repo)
    MODEL_BACKEND_IMAGE: mygit.th-deg.de:5050/schober-teaching/student-projects/ain-23-software-engineering/ss-25/icebergai/model-backend:latest
  before_script:
    - apk add --no-cache git
    # Use the cicdtoken to authenticate Git submodule access
    - git config --global http.extraheader "PRIVATE-TOKEN: ${cicdtoken}"
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    # Log in to GitLab Container Registry using the bot account
    - docker login -u "group_18068_bot_ad5513e4e5687a027b8876f444416439a" -p "${cicdtoken}" mygit.th-deg.de:5050
    # Build the model-backend image from its submodule
    - docker build -t $MODEL_BACKEND_IMAGE ./model-backend
    # Push to model-backend's registry
    - docker push $MODEL_BACKEND_IMAGE
  rules:
    - if: $CI_COMMIT_BRANCH == "main"  # Adjust if your default branch is different