stages:
  - test
  - docker-test

test_pipeline:
  stage: test
  image: alpine:latest
  script:
    - echo "Basic pipeline works!"

docker_test:
  stage: docker-test
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker info
    - docker run hello-world
    - echo "Docker is working!"

registry_test:
  stage: docker-test
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker info
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - echo "Registry login successful!"