stages:
  - build

build_docker_images:
  image: docker:latest
  services:
    - docker:20.10.7-dind  # Use a specific DIND version
  variables:
    # Configure Docker to connect to DIND service
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""  # Disable TLS for simplicity
  before_script:
    # Install Docker Compose without using pip
    - apk add --no-cache curl
    - curl -L "https://github.com/docker/compose/releases/download/v2.25.0/docker-compose- $(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker-compose build
    - docker-compose push