# .gitlab-ci.yml

stages:
  - build  # ONLY the 'build' stage exists

build_docker_images:
  stage: build  # Explicitly assign to 'build'
  image: docker:latest
  services:
    - docker:20.10.7-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache curl
    - curl -L "https://github.com/docker/compose/releases/download/v2.25.0/docker-compose- $(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker-compose build
    - docker-compose push