.build_and_push_template:
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  before_script: |
    set -exo pipefail

    # Ping the registry host (DNS resolution check)
    echo "Attempting to ping registry host: mygit.th-deg.de"
    ping -c 3 mygit.th-deg.de || true # || true to prevent job failure if ping fails

    # Check TCP connectivity to the registry port
    echo "Attempting to telnet to registry: mygit.th-deg.de:5050"
    # Using netcat (nc) as telnet might not be in docker:latest, and it's better for scripting
    nc -vz mygit.th-deg.de 5050 || true # || true to prevent job failure if connection fails

    while ! docker info; do sleep 1; done
    docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

    echo "Listing files in the project root: $CI_PROJECT_DIR"
    ls -la "$CI_PROJECT_DIR"
    echo "---------------------"
  script: |
    echo "Attempting to build image: $CI_REGISTRY_IMAGE from context: $CI_PROJECT_DIR/$BUILD_CONTEXT_DIR"
    docker build -t "$CI_REGISTRY_IMAGE" "$CI_PROJECT_DIR/$BUILD_CONTEXT_DIR"
    echo "Build successful. Now attempting to push image: $CI_REGISTRY_IMAGE"
    docker push "$CI_REGISTRY_IMAGE"
    echo "Image push command completed. Check registry."
# ... rest of your jobs ...