stages:
  - build

variables:
  CI_IMAGE_PREFIX: mygit.th-deg.de:5050/schober-teaching/student-projects/ain-23-software-engineering/ss-25/icebergai
  DOCKER_TLS_CERTDIR: "/certs"

.build_and_push_template:
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  before_script:
    - echo "Executing before_script" # Drastically simplified
  script:
    - echo "Skipping build for test" # Simplified for quick test
    # - docker build -t "$CI_REGISTRY_IMAGE" "$CI_PROJECT_DIR/$BUILD_CONTEXT_DIR"
    # - docker push "$CI_REGISTRY_IMAGE"

build-web-frontend:
  stage: build
  extends: .build_and_push_template
  variables:
    CI_REGISTRY_IMAGE: "$CI_IMAGE_PREFIX/web-frontend:latest"
    BUILD_CONTEXT_DIR: "web-frontend"

# (Include other jobs, but focus on web-frontend for linting)
# build-web-backend:
#   stage: build
#   extends: .build_and_push_template
#   variables:
#     CI_REGISTRY_IMAGE: "$CI_IMAGE_PREFIX/web-backend:latest"
#     BUILD_CONTEXT_DIR: "web-backend"

# build-model-backend:
#   stage: build
#   extends: .build_and_push_template
#   variables:
#     CI_REGISTRY_IMAGE: "$CI_IMAGE_PREFIX/model-backend:latest"
#     BUILD_CONTEXT_DIR: "model-backend"