stages:
  - check
  - test

placeholder_job:
  stage: check
  script:
    - echo "No CI checks required for this project"

nightly_e2e_tests:
  stage: test
  image: docker/compose:alpine-1.29.2
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  before_script:
    - until docker info; do sleep 1; done
  script:
    - docker-compose run --rm playwright npx playwright test
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
    expire_in: 30 days
  only:
    - schedules
  allow_failure: true
