stages:
  - build

variables:
  CI_REGISTRY: "registry.mygit.th-deg.de"
  CI_REGISTRY_IMAGE: "${CI_REGISTRY}/schober-teaching/student-projects/ain-23-software-engineering/ss-25/icebergai"
  DOCKER_HOST: tcp://localhost:2375  # Use localhost instead of docker
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

build-images:
  stage: build
  image: docker:24.0.7
  services:
    - name: docker:24.0.7-dind
      command: ["--host", "tcp://0.0.0.0:2375", "--storage-driver=overlay2"]
  script:
    - sleep 5  # Wait for DinD to initialize
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "${CI_REGISTRY_IMAGE}/web-frontend:latest" "./frontend"
    - docker build -t "${CI_REGISTRY_IMAGE}/web-backend:latest" "./backend"
    - docker build -t "${CI_REGISTRY_IMAGE}/model-backend:latest" "./model-backend"
    - docker push "${CI_REGISTRY_IMAGE}/web-frontend:latest"
    - docker push "${CI_REGISTRY_IMAGE}/web-backend:latest"
    - docker push "${CI_REGISTRY_IMAGE}/model-backend:latest"