stages:
  - check
  - test

placeholder_job:
  stage: check
  script:
    - echo "No CI checks required for this project"

nightly_e2e_tests:
  stage: test
  script:
    - docker-compose run --rm playwright npx playwright test
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
    expire_in: 1 week
  only:
    - schedules
  allow_failure: true
