stages:
  - build

variables:
  # GitLab Container Registry URL
  CI_REGISTRY: "registry.mygit.th-deg.de"
  # Project-specific image path
  CI_REGISTRY_IMAGE: "${CI_REGISTRY}/schober-teaching/student-projects/ain-23-software-engineering/ss-25/icebergai"
  # Docker-in-Docker (DinD) settings
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

# Build and push web-frontend
build-frontend:
  stage: build
  image: docker:24.0.7
  services:
    - name: docker:dind
      command: ["--tls=false", "--host", "tcp://0.0.0.0:2375"]
  variables:
    SERVICE_DIR: "frontend"
    IMAGE_NAME: "${CI_REGISTRY_IMAGE}/web-frontend:latest"
  script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$IMAGE_NAME" "./$SERVICE_DIR"
    - docker push "$IMAGE_NAME"

# Build and push web-backend
build-backend:
  stage: build
  image: docker:24.0.7
  services:
    - name: docker:dind
      command: ["--tls=false", "--host", "tcp://0.0.0.0:2375"]
  variables:
    SERVICE_DIR: "backend"
    IMAGE_NAME: "${CI_REGISTRY_IMAGE}/web-backend:latest"
  script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$IMAGE_NAME" "./$SERVICE_DIR"
    - docker push "$IMAGE_NAME"

# Build and push model-backend
build-model-backend:
  stage: build
  image: docker:24.0.7
  services:
    - name: docker:dind
      command: ["--tls=false", "--host", "tcp://0.0.0.0:2375"]
  variables:
    SERVICE_DIR: "model-backend"
    IMAGE_NAME: "${CI_REGISTRY_IMAGE}/model-backend:latest"
  script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$IMAGE_NAME" "./$SERVICE_DIR"
    - docker push "$IMAGE_NAME"