stages:
  - build

variables:
  # Define the base image path for your container registry
  CI_IMAGE_PREFIX: mygit.th-deg.de:5050/schober-teaching/student-projects/ain-23-software-engineering/ss-25/icebergai

# This template job defines the common steps for building and pushing Docker images.
.build_and_push_template: &build_and_push_definition
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    # Log in to the GitLab container registry
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    # Build the Docker image
    - docker build -t "$CI_REGISTRY_IMAGE" -f "$DOCKERFILE_PATH" "$BUILD_CONTEXT"
    # Push the Docker image to the container registry
    - docker push "$CI_REGISTRY_IMAGE"

build-web-frontend:
  # Inherit the common steps from the template
  <<: *build_and_push_definition
  variables:
    # Define the specific variables for this job
    CI_REGISTRY_IMAGE: "$CI_IMAGE_PREFIX/web-frontend:latest"
    DOCKERFILE_PATH: "web-frontend/Dockerfile"
    BUILD_CONTEXT: "web-frontend"

build-web-backend:
  <<: *build_and_push_definition
  variables:
    CI_REGISTRY_IMAGE: "$CI_IMAGE_PREFIX/web-backend:latest"
    DOCKERFILE_PATH: "web-backend/Dockerfile"
    BUILD_CONTEXT: "web-backend"

build-model-backend:
  <<: *build_and_push_definition
  variables:
    CI_REGISTRY_IMAGE: "$CI_IMAGE_PREFIX/model-backend:latest"
    DOCKERFILE_PATH: "model-backend/Dockerfile"
    BUILD_CONTEXT: "model-backend"