stages:
  - check
  - test

placeholder_job:
  stage: check
  script:
    - echo "No checks needed; this is just a placeholder."
  allow_failure: true
  only:
    - merge_requests

nightly_e2e_tests:
  stage: test
  image: docker/compose:alpine-1.29.2
  services:
    - name: docker:20.10.16-dind
      alias: docker
      command: ["--tls=false", "--host", "tcp://0.0.0.0:2375"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker info
    - docker-compose up -d --build
    - sleep 10
  script:
    - docker-compose run --rm playwright npx playwright test
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
    expire_in: 30 days
  only:
    - schedules
  allow_failure: true
