stages:
  - test

nightly_e2e_tests:
  stage: test
  image: docker/compose:alpine-1.29.2
  services:
    - name: docker:20.10.16-dind
      alias: docker-dind
      command: ["--tls=false", "--host", "tcp://0.0.0.0:2375"]

  variables:
    DOCKER_HOST: tcp://docker-dind:2375
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - docker info
    - docker-compose up -d --build
    - sleep 15

  script:
    - docker-compose run --rm playwright npx playwright test || echo "Tests failed - continuing to collect artifacts"

  after_script:
    - docker-compose down

  artifacts:
    when: always
    paths:
      - ./playwright-report/
      - ./test-results/
    reports:
      junit: ./test-results/*.xml
    expire_in: 30 days

  only:
    - schedules
  allow_failure: true
