stages:
  - build

build-frontend:
  stage: build
  image: docker:24.0.7
  services:
    - name: docker:dind
      command: ["--tls=false", "--host", "tcp://0.0.0.0:2375"]
  script:
    - echo "Hello World"