stages:
  - build

variables:
  CI_REGISTRY: "registry.mygit.th-deg.de"
  CI_REGISTRY_IMAGE: "${CI_REGISTRY}/schober-teaching/student-projects/ain-23-software-engineering/ss-25/icebergai"

build-frontend:
  stage: build
  image: docker:24.0.7
  services:
    - docker:dind
  variables:
    SERVICE_DIR: "frontend"
    IMAGE_NAME: "${CI_REGISTRY_IMAGE}/web-frontend:latest"
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE_NAME ./$SERVICE_DIR
    - docker push $IMAGE_NAME

build-backend:
  stage: build
  image: docker:24.0.7
  services:
    - docker:dind
  variables:
    SERVICE_DIR: "backend"
    IMAGE_NAME: "${CI_REGISTRY_IMAGE}/web-backend:latest"
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE_NAME ./$SERVICE_DIR
    - docker push $IMAGE_NAME

build-model-backend:
  stage: build
  image: docker:24.0.7
  services:
    - docker:dind
  variables:
    SERVICE_DIR: "model-backend"
    IMAGE_NAME: "${CI_REGISTRY_IMAGE}/model-backend:latest"
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE_NAME ./$SERVICE_DIR
    - docker push $IMAGE_NAME